apiDir: "../headless-workflow-api/src/main/java"
apiPackagePath: "com.liferay.headless.workflow"
application:
    baseURI: "/headless-workflow"
    className: "HeadlessWorkflowApplication"
    name: "headless-workflow-application"
author: "Javier Gamarra"