components:
  schemas:
    Comment:
      description: https://www.schema.org/Comment
      properties:
        comments:
          items:
            $ref: "#/components/schemas/Comment"
          type: array
        creator:
          $ref: "#/components/schemas/Creator"
        id:
          format: int64
          type: integer
        self:
          format: uri
          type: string
        text:
          type: string
      type: object
    Creator:
      description: https://www.schema.org/Creator
      properties:
        additionalName:
          type: string
        alternateName:
          type: string
        email:
          type: string
        familyName:
          type: string
        givenName:
          type: string
        id:
          format: int64
          type: integer
        image:
          format: uri
          type: string
        jobTitle:
          type: string
        name:
          type: string
        profileURL:
          type: string
        self:
          format: uri
          type: string
      type: object
    Document:
      description: https://www.schema.org/Document
      properties:
        adaptedMedia:
          description: https://www.schema.org/ImageObject
          properties:
            contentUrl:
              format: uri
              type: string
            height:
              type: number
            id:
              format: int64
              type: integer
            resolutionName:
              type: string
            self:
              format: uri
              type: string
            sizeInBytes:
              type: number
            width:
              type: number
          type: object
        category:
          items:
            format: int64
            type: integer
          type: array
        contentUrl:
          format: uri
          type: string
        creator:
          $ref: "#/components/schemas/Creator"
        dateCreated:
          format: date-time
          type: string
        dateModified:
          format: date-time
          type: string
        description:
          type: string
        encodingFormat:
          type: string
        fileExtension:
          type: string
        folder:
          allOf:
            - $ref: "#/components/schemas/Folder"
          readOnly: true
        folderId:
          format: int64
          type: integer
          writeOnly: true
        id:
          format: int64
          type: integer
        keywords:
          items:
            type: string
          type: array
        self:
          format: uri
          type: string
        sizeInBytes:
          type: number
        title:
          type: string
      type: object
    Folder:
      description: https://www.schema.org/Folder
      properties:
        dateCreated:
          format: date-time
          type: string
        dateModified:
          format: date-time
          type: string
        description:
          type: string
        documents:
          items:
            $ref: "#/components/schemas/Document"
          readOnly: true
          type: array
        documentsIds:
          items:
            format: int64
            type: integer
          type: array
          writeOnly: true
        documentsRepository:
          allOf:
            - $ref: "#/components/schemas/Folder"
          readOnly: true
        documentsRepositoryId:
          format: int64
          type: integer
          writeOnly: true
        id:
          format: int64
          type: integer
        name:
          type: string
        self:
          format: uri
          type: string
        subFolders:
          items:
            $ref: "#/components/schemas/Folder"
          type: array
      type: object
info:
  description: ""
  title: ""
  version: v1.0
openapi: 3.0.1
paths:
  "/creator/{creator-id}":
    get:
      parameters:
        - in: path
          name: creator-id
          required: true
          schema:
            format: int64
            type: integer
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Creator"
          description: ""
  "/document/{document-id}":
    delete:
      parameters:
        - in: path
          name: document-id
          required: true
          schema:
            format: int64
            type: integer
      responses:
        204:
          content:
            application/json: {}
          description: ""
    get:
      parameters:
        - in: path
          name: document-id
          required: true
          schema:
            format: int64
            type: integer
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Document"
          description: ""
  "/document/{document-id}/categories":
    get:
      parameters:
        - in: query
          name: page
          schema:
            type: integer
        - in: query
          name: per_page
          schema:
            type: integer
        - in: path
          name: document-id
          required: true
          schema:
            format: int64
            type: integer
      responses:
        200:
          content:
            application/json:
              schema:
                items:
                  format: int64
                  type: integer
                type: array
          description: ""
    post:
      parameters:
        - in: path
          name: document-id
          required: true
          schema:
            format: int64
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              format: int64
              type: integer
      responses:
        200:
          content:
            application/json:
              schema:
                format: int64
                type: integer
          description: ""
  "/document/{document-id}/categories/batch-create":
    post:
      parameters:
        - in: path
          name: document-id
          required: true
          schema:
            format: int64
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              format: int64
              type: integer
      responses:
        200:
          content:
            application/json:
              schema:
                format: int64
                type: integer
          description: ""
  "/document/{document-id}/comment":
    get:
      parameters:
        - in: query
          name: page
          schema:
            type: integer
        - in: query
          name: per_page
          schema:
            type: integer
        - in: path
          name: document-id
          required: true
          schema:
            format: int64
            type: integer
      responses:
        200:
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/Comment"
                type: array
          description: ""
  "/documents-repository/{id}":
    get:
      parameters:
        - in: path
          name: id
          required: true
          schema:
            format: int64
            type: integer
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Folder"
          description: ""
  "/documents-repository/{documents-repository-id}/document":
    get:
      parameters:
        - in: query
          name: page
          schema:
            type: integer
        - in: query
          name: per_page
          schema:
            type: integer
        - in: path
          name: documents-repository-id
          required: true
          schema:
            format: int64
            type: integer
      responses:
        200:
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/Document"
                type: array
          description: ""
    post:
      parameters:
        - in: path
          name: documents-repository-id
          required: true
          schema:
            format: int64
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Document"
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Document"
          description: ""
  "/documents-repository/{documents-repository-id}/document/batch-create":
    post:
      parameters:
        - in: path
          name: documents-repository-id
          required: true
          schema:
            format: int64
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Document"
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Document"
          description: ""
  "/documents-repository/{documents-repository-id}/folder":
    get:
      parameters:
        - in: query
          name: page
          schema:
            type: integer
        - in: query
          name: per_page
          schema:
            type: integer
        - in: path
          name: documents-repository-id
          required: true
          schema:
            format: int64
            type: integer
      responses:
        200:
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/Folder"
                type: array
          description: ""
    post:
      parameters:
        - in: path
          name: documents-repository-id
          required: true
          schema:
            format: int64
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Folder"
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Folder"
          description: ""
  "/documents-repository/{documents-repository-id}/folder/batch-create":
    post:
      parameters:
        - in: path
          name: documents-repository-id
          required: true
          schema:
            format: int64
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Folder"
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Folder"
          description: ""
  "/folder/{folder-id}":
    delete:
      parameters:
        - in: path
          name: folder-id
          required: true
          schema:
            format: int64
            type: integer
      responses:
        204:
          content:
            application/json: {}
          description: ""
    get:
      parameters:
        - in: path
          name: folder-id
          required: true
          schema:
            format: int64
            type: integer
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Folder"
          description: ""
    put:
      parameters:
        - in: path
          name: folder-id
          required: true
          schema:
            format: int64
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Folder"
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Folder"
          description: ""
  "/folder/{folder-id}/document":
    get:
      parameters:
        - in: query
          name: page
          schema:
            type: integer
        - in: query
          name: per_page
          schema:
            type: integer
        - in: path
          name: folder-id
          required: true
          schema:
            format: int64
            type: integer
      responses:
        200:
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/Document"
                type: array
          description: ""
    post:
      parameters:
        - in: path
          name: folder-id
          required: true
          schema:
            format: int64
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Document"
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Document"
          description: ""
  "/folder/{folder-id}/document/batch-create":
    post:
      parameters:
        - in: path
          name: folder-id
          required: true
          schema:
            format: int64
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Document"
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Document"
          description: ""
  "/folder/{folder-id}/folder":
    get:
      parameters:
        - in: query
          name: page
          schema:
            type: integer
        - in: query
          name: per_page
          schema:
            type: integer
        - in: path
          name: folder-id
          required: true
          schema:
            format: int64
            type: integer
      responses:
        200:
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/Folder"
                type: array
          description: ""
    post:
      parameters:
        - in: path
          name: folder-id
          required: true
          schema:
            format: int64
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Folder"
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Folder"
          description: ""
  "/folder/{folder-id}/folder/batch-create":
    post:
      parameters:
        - in: path
          name: folder-id
          required: true
          schema:
            format: int64
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Folder"
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Folder"
          description: ""